apiVersion: apps/v1
kind: Deployment
metadata:
  name: aurorainfra-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aurorainfra-backend
  template:
    metadata:
      labels:
        app: aurorainfra-backend
    spec:
      containers:
      - name: backend
        image: aurorainfra/backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: postgres://user:password@db:5432/mydatabase
---
apiVersion: v1
kind: Service
metadata:
  name: aurorainfra-backend-service
spec:
  selector:
    app: aurorainfra-backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aurorainfra-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aurorainfra-frontend
  template:
    metadata:
      labels:
        app: aurorainfra-frontend
    spec:
      containers:
      - name: frontend
        image: aurorainfra/frontend:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: aurorainfra-frontend-service
spec:
  selector:
    app: aurorainfra-frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer